### ISSUE TITLE
weewx dies when running the brultech driver

### ISSUE THREAD

**Issue by matthewwall** [tkeffer/weepwr#1]
looks like some assumptions in brultech.py might not consider all of the cases.

```
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__: Caught unrecoverable exception:
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****  integer division or modulo by zero
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****  Traceback (most recent call last):
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****    File "/opt/weewx/bin/weewxd", line 153, in main
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****      engine.run()
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****    File "/opt/weewx/bin/weewx/engine.py", line 210, in run
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.NEW_LOOP_PACKET, packet=packet))
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****    File "/opt/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****      callback(event)
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****    File "/opt/weewx/bin/user/brultech.py", line 911, in new_loop_packet
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****      self.bt_extends.add_power_to_packet(event.packet)
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****    File "/opt/weewx/bin/user/brultech.py", line 781, in add_power_to_packet
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****      deriv = self.derivatives[obs_type].add_record(packet)
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****    File "/opt/weewx/bin/weeutil/timediff.py", line 44, in add_record
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****      derivative = (record[self.obs_type] - self.old_value) / (record['dateTime'] - self.old_timestamp)
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****  ZeroDivisionError: integer division or modulo by zero
Dec 24 12:05:22 pitest weewx-gem[6912] CRITICAL __main__:     ****  Exiting.
```

this is weewx development branch as of 23dec2021 and brultech driver as of a few days ago.

here is the log from startup:
```
Dec 24 22:20:59 pitest weewx-gem[10386] INFO __main__: Initializing weewx version 4.6.0b7
Dec 24 22:20:59 pitest weewx-gem[10386] INFO __main__: Using Python 2.7.16 (default, Oct 10 2019, 22:02:15) #012[GCC 8.3.0]
Dec 24 22:20:59 pitest weewx-gem[10386] INFO __main__: Platform Linux-5.10.63-v7+-armv7l-with-debian-10.11
Dec 24 22:20:59 pitest weewx-gem[10386] INFO __main__: Locale is 'en_GB.UTF-8'
Dec 24 22:20:59 pitest weewx-gem[10386] INFO __main__: Using configuration file /etc/weewx/gem.conf
Dec 24 22:20:59 pitest weewx-gem[10386] INFO __main__: Debug is 0
Dec 24 22:20:59 pitest weewx-gem[10386] INFO __main__: PID file is /var/run/weewx-gem.pid
Dec 24 22:20:59 pitest weewx-gem[10390] INFO weewx.engine: Loading station type Brultech (user.brultech)
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.engine: StdConvert target unit is 0x1
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.wxservices: StdWXCalculate will use data binding bt_binding
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.engine: Archive will use data binding bt_binding
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.engine: Record generation will be attempted in 'hardware'
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.engine: Using archive interval of 300 seconds (specified in weewx configuration)
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.restx: StationRegistry: Registration not requested.
Dec 24 22:21:00 pitest weewx-gem[10390] INFO user.influx: service version is 0.16
Dec 24 22:21:00 pitest weewx-gem[10390] INFO user.influx: database: data
Dec 24 22:21:00 pitest weewx-gem[10390] INFO user.influx: destination: http://192.168.76.60/influx
Dec 24 22:21:00 pitest weewx-gem[10390] INFO user.influx: line_format: multi-line-dotted
Dec 24 22:21:00 pitest weewx-gem[10390] INFO user.influx: measurement: pitest.gem
Dec 24 22:21:00 pitest weewx-gem[10390] INFO user.influx: tags: host=pitest,driver=gem
Dec 24 22:21:00 pitest weewx-gem[10390] INFO user.influx: binding: loop,archive
Dec 24 22:21:00 pitest weewx-gem[10390] INFO user.influx: Data will be uploaded to http://192.168.76.60/influx
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.engine: 'pyephem' not detected, extended almanac data is not available
Dec 24 22:21:00 pitest weewx-gem[10390] INFO __main__: Starting up weewx version 4.6.0b7
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.engine: Clock error is 1.06 seconds (positive is fast)
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.engine: Using binding 'bt_binding' to database 'gem.sdb'
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.manager: Starting backfill of daily summaries
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.manager: Daily summaries up to date
Dec 24 22:21:00 pitest weewx-gem[10390] INFO weewx.engine: Starting main packet loop.
```

let me know if you need debug

**Comment by tkeffer** [comment]
Sorry. I just saw this.

For some reason, the Brultech is emitting sequential packets that have the same time stamp. Can you think of any reason why this would be?

In any case, the driver shouldn't crash if this happens. I'll have the derivative algorithm return `None` if this happens.

**Comment by tkeffer** [comment]
OK. Hopefully fixed in commit https://github.com/weewx/weewx/commit/1da37ff7a44849384a8ea562e39f9fc94b609f67
